# Generated by Django 5.1.4 on 2024-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFES6', '0005_rename_courseid_todo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='titleClass',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='correction_td_tp',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='td',
            name='titleTd',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tp',
            name='titleTp',
            field=models.CharField(max_length=250),
        ),
    ]
